// qwik-product-explorer/src/components/FavoriteButton.tsx
import { $, component$, useSignal, useVisibleTask$ } from "@builder.io/qwik";

interface FavoriteButtonProps {
  productId: number;
}

const STORAGE_KEY = "favoriteProducts";

export default component$<FavoriteButtonProps>(({ productId }) => {
  const isFavorite = useSignal(false);

  useVisibleTask$(() => {
    try {
      const storedFavorites = window.localStorage.getItem(STORAGE_KEY);

      if (!storedFavorites) {
        isFavorite.value = false;
        return;
      }

      const favorites = JSON.parse(storedFavorites);

      if (Array.isArray(favorites)) {
        isFavorite.value = favorites.includes(productId);
      }
    } catch {
      isFavorite.value = false;
    }
  });

  const toggleFavorite = $(() => {
    try {
      const storedFavorites = window.localStorage.getItem(STORAGE_KEY);
      const parsedFavorites = storedFavorites
        ? JSON.parse(storedFavorites)
        : [];

      const favorites: number[] = Array.isArray(parsedFavorites)
        ? parsedFavorites.filter((id) => typeof id === "number")
        : [];

      const nextFavorites = favorites.includes(productId)
        ? favorites.filter((id) => id !== productId)
        : [...favorites, productId];

      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(nextFavorites));
      isFavorite.value = nextFavorites.includes(productId);
    } catch {
      isFavorite.value = !isFavorite.value;
    }
  });

  return (
    <button
      type="button"
      class={isFavorite.value ? "favorite-button active" : "favorite-button"}
      onClick$={toggleFavorite}
      aria-pressed={isFavorite.value}
      aria-label={
        isFavorite.value ? "Remove from favorites" : "Add to favorites"
      }
      title={isFavorite.value ? "Remove from favorites" : "Add to favorites"}
    >
      ♥
    </button>
  );
});

// sveltekit-product-explorer/src/lib/components/FavoriteButton.svelte
<script lang="ts">
	interface Props {
		productId: number;
	}

	let { productId }: Props = $props();

	let isFavorite = $state(false);

	function loadFavorite() {
		if (typeof window !== 'undefined') {
			const favorites = JSON.parse(localStorage.getItem('favorites') || '[]');
			isFavorite = favorites.includes(productId);
		}
	}

	function toggleFavorite() {
		let favorites = JSON.parse(localStorage.getItem('favorites') || '[]');

		if (favorites.includes(productId)) {
			favorites = favorites.filter((id: number) => id !== productId);
			isFavorite = false;
		} else {
			favorites.push(productId);
			isFavorite = true;
		}

		localStorage.setItem('favorites', JSON.stringify(favorites));
	}

	loadFavorite();
</script>

<button
	class="favorite-button"
	class:active={isFavorite}
	onclick={toggleFavorite}
	aria-label={isFavorite ? 'Remove from favorites' : 'Add to favorites'}
>
	{isFavorite ? '♥' : '♡'}
</button>

<style>
	.favorite-button {
		background: #fff;
		border: 2px solid #ff1744;
		color: #ff1744;
		padding: 8px 12px;
		border-radius: 4px;
		cursor: pointer;
		font-size: 1.2rem;
		transition: all 0.2s ease;
	}

	.favorite-button:hover {
		background: #ffebee;
	}

	.favorite-button.active {
		background: #ff1744;
		color: #fff;
	}

	.favorite-button.active:hover {
		background: #d01040;
	}
</style>
